server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:producer_db}"
    username: "${DB_USERNAME:postgres}"
    password: "${DB_PASSWORD:postgres}"

  jpa:
    hibernate:
      ddl-auto: none   # ?.?. Flyway ????????
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  kafka:
    bootstrap-servers: "${KAFKA_HOST_1:localhost}:${KAFKA_PORT_1:9092},${KAFKA_HOST_2:localhost}:${KAFKA_PORT_2:9092}"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.kafka.producer.value-json-type: ru.arsentiev.producer.entity.Item
        spring.json.add.type.headers: false


producer:
  kafka:
    topic: "items-topic"
